### PR TITLE
Bugfix, and test changes

### PR DESCRIPTION
**Pull request by alexhughson**
The code was crashing when I entered a page where the #hashvalue was unspecified, and I had a rescue function defined.

The code to fix it was used elsewhere, so I moved it to a helper function, and called it from both.

Tests are updated, but currently there is no test for the Path.root function, because testing the error I had could not be done at the same time.  Sometime I will add another test.

### CODE REVIEW

**Comment by mtrpcic** [comment]
I don't appear to be getting this error using the latest version of PathJS.  If you get the latest, type "Path.version" in your debugger console and see if it has a value (It will be 0.5 for the latest version, or undefined for anything else, since it was just added).

**Comment by mtrpcic** [comment]
I'm using the example code [here](http://pastie.org/2011735) to try to reproduce the bug you're mentioning.  I'm using the latest version of Path.js (Path.version == "0.5").  Please modify the example to show the flaw and I'll work on merging the pull request.

**Comment by alexhughson** [comment]
Looking at the code, you seem to have fixed it.  

Only difference in mine was that the code was in a helper function, so that the two places that did it used the same code.  No big deal.

**Comment by mtrpcic** [comment]
Thanks for helping out.  I'm going to be spending some time in the near future cleaning up code, and breaking things out into more convenient helper functions.  Feel free to contribute in the future :)

**Pull request closed without merging**
